# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username: admin_t
  password: t0ps3cr3t
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *common
  database: ticketee_development



test: &test
  <<: *common
  database: ticketee_test

production:
  <<: *common
  database: ticketee_production

cucumber:
  <<: *test